apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-api
  template:
    metadata:
      labels:
        app: e-commerce-api
    spec:
      containers:
      - name: e-commerce-api
        image: ghcr.io/brian432-cpu/e-commerce-with-aws:34ef3bc3a8868e76d13140b0c81f39298501bb9e
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: BETTER_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: BETTER_AUTH_SECRET
        - name: BETTER_AUTH_URL
          value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce-api
  namespace: default
spec:
  selector:
    app: e-commerce-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

